### ISSUE TITLE
Issue with HDF names and configs & Issue with mounting them correctly

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#14]
Hiya, I noticed you started working on the ConfigMaker again for the new Amiberry version, so I gave your Development version a whirl. I still can't get it to detect and correct the filenames of HDF Data Only files (one of your comments said it was fixed ?), I have my files set as follows -

amiga-data
.....Games_WHDLoad_HDF
..........AlienBreedTA11AGA.hdf
..........ArcadePoolAGA.hdf
..........BansheeAGA.hdf
etc.

I also tried putting them in 'Games_WHDLoad_AGA_HDF' but it won't rename the UAE files correctly (with spaces etc.) This also means it's probably not applying the Game specific option changes (like fast copper, blitter etc.) ?

The other thing was that when selecting a game and it gets to 'Creating WHDLoad BootScript' I kept getting an AMOS window pop up (The Booter is written in AMOS ?) saying the 'Volume is write protected'. I looked in the GUI and found out that the Config Maker is mounting the Data Only HDF's in DH1 as 'directories' instead of mounting as 'Hardfiles'. I mounted them manually and it worked.

I hope these can be fixed because as I have said before, personally I think HDF's are cleaner and less files all over the SD card. I know it will be a slight pain to update to newer versions but I can do this manually and Stingray has said that you shouldn't extract updated Slave packages over the top of old ones anyway.

(I posted some Data Only HDF's in the other thread https://github.com/HoraceAndTheSpider/UAEConfigMaker/issues/12 a few months ago which you asked for. I will probably close that issue soon as it's a bit messy).

**Comment by HoraceAndTheSpider** [comment]
i am still running through a big list of fixes/changes so i will check the `Games_WHDLoad_AGA_HDF` path and the mounting of the HDF drive path - thanks for the heads up.

Whilst some changes to games require a full re-install (due to changes in data layout, or the way data is extracted from the original disks) many slaves get updated and still work with the previously-installed data. So whilst StingRay is vastly experienced with amiga slave writing, with-respect he is not responsible for this project, and the usage he would no doubt prefer is to install each game 'as new' after an update. This is simply not going to be practical for the experience level of end-user being targetted for this project. 

Myself and @osvaldolove therefore will be continuing to look at slave updating features, which should aid most users who have little familiarity with WHDLoad and would not be comfortable re-installing games from scratch. Whilst we can't make this work for 100% of slave updates (due to the parts mentioned above) i feel we can realistically target this working on 90%+ of slave updates.

For now, the booter program will still require the auto-startup script to be placed alongside the game data (simply becuase they are game specific, and to keep these in DH0 will slow down loading whilst the names are matched on a game-by-game basis) so there is always going to be a need to write to the DH1: drive. Maybe this will change in the future, but not soon.  

Whilst i will add all the support i can for HDF usage, this does not remain my target use-case, for the reasons explained previously.

**Comment by HoraceAndTheSpider** [comment]
Hmm.. No problem getting the rename of HDFs to work here:
http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/debug/alfred.png


Please check that the code is definately running with `version 3.0` displayed.

There also seems to be no reason why the HDF wouldnt be correctly mounted: 

http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/debug/alfred2.png

I will double-check the syntax on that though.


However, it has occured to me that if you are still using the 'auto-update' features, then the config template and other files will be pulled from the 'master' branch rather than the 'develop' branch. You would need to manually update the tempalte config file, and use the --no-update option whilst running the development version.

**Comment by ghost** [comment]
I redownloaded the development version and ran it with -n attached. The UAE config files it made are not renamed (they are the same as the HDF filenames). I checked one of the UAE configs and it says v3.5.0. It's still mounting as a directory though. If I go into the GUI and click the '...' next to DH1 it just gives the directory path instead of showing sufaces,reserved,sectors and blocksize.

**Comment by ghost** [comment]
I manually mounted the hardfile and saved the config, it shows this -

```
filesystem2=rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
uaehf0=dir,rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
hardfile2=rw,DH1:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,32,1,2,512,0,,uae
uaehf1=hdf,rw,DH1:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,32,1,2,512,0,,uae
```
This is what was originally in the config -

```
filesystem2=rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
uaehf1=dir,rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
;filesystem2=rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf/,0
;uaehf0=dir,rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf/,0
filesystem2=rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,0,1,2,512,50,,uae
hardfile2=dir,rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,0,1,2,512,50,,uae

```

**Comment by HoraceAndTheSpider** [comment]
There are two issues here, and it is difficult to fix one without resolving the other first.  The problem of mouting an HDF as a folder is probably because the correct 'scan mode' is not being called, which causes your HDFs to be mounted wrong.

The renaming of HDFs should show [WHDLoad HDF]  in the end of the file, if the scanning is working correctly. I have tested myself using the 4 HDFs you uploaded before, and i do not have this problem.

Can you post the full output of the terminal when running please (upload to pastebin if needed everything , including `"HoraceAndTheSpider's UAE Configuration Maker (3.0)"`)
in particualr i need to see the section like this:

```Config Save Path: /Users/horaceandthespider/Documents/Gaming/AmigaWHD/WorkingFolder2/Test/
Games Files Path: Games_WHDLoad_HDF_AGA

Scan Mode: WHDLoadHDF

1: Processing Game: AlienBreedTA11AGA.hdf

     Full Name: Alien Breed Tower Assault (v1.1) [AGA] [WHDLoad HDF]
     Editing File: /Users/horaceandthespider/Documents/Gaming/AmigaWHD/WorkingFolder2/Test/Alien Breed Tower Assault (v1.1) [AGA] [WHDLoad HDF].uae

```

I would also recommend you do use `Games_WHDLoad_HDF_AGA` for AGA games, as you mentioend previously, otherwise it could set the emualted amiga settings wrong (it shouldnt, but could do whilst the renaming is not working)

Thanks

**Comment by ghost** [comment]
I decided to burn a new RetroPie image. I Copied the AGA HDF's to `Games_WHDLoad_HDF_AGA` and ran the config maker with -n, now it has renamed them correctly (With `[AGA] [WHDLoad HDF]` on the end) ! I'm not sure what happened. The configs still seem to be mounted as a directory though. 

```
filesystem2=rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
uaehf1=dir,rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
;filesystem2=rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf/,0
;uaehf0=dir,rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf/,0
filesystem2=rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,0,1,2,512,50,,uae
hardfile2=dir,rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,0,1,2,512,50,,uae
```

As you can see it still says `dir` in the filepath signifying a directory ? and the numbers at the end of the path are different to what it shows when you manually mount it (as I showed a couple of posts above).

**Comment by HoraceAndTheSpider** [comment]
Glad to hear that worked!  possibly there was some mix-up with the location of the config maker script and you werent getting the benefit of the recent fixes entirely. 

I've pushed a few tweaks to the HDF section, using your provided info as a basis, hopefully that might fix the above. It looks right, but i actually dont have access to a pi to test on at the moment, i am just running the script on my laptop and locally held files.

You may have to manually update the `uae_config_maker.py`, although i have also just pushed a change to `update_config_maker.py` which will grab the latest files from the develop branch. (That script, if run first, *should* update the main config maker script for you)

**Comment by ghost** [comment]
Unfortunately, it now says '0 Slaves found' !

**Comment by HoraceAndTheSpider** [comment]
the drives persumably are now mounted correctly?  The slave selection process is done by the booter, and possibly the content is laid out in a way which it cannot pick up

Please go to the amiga DOS screen (ctrl-D or Ctrl-C) and post a screenshot of the output of `dir opt -a DH0:` and `dir opt -a DH1:`

**Comment by ghost** [comment]
If I go to the GUI nothing is mounted in DH1: 

This is what the file looks like now -
```
filesystem2=rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
uaehf0=dir,rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
;filesystem2=rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF_AGA/BubbleAndSqueakAGA.hdf/,0
;uaehf1=dir,rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF_AGA/BubbleAndSqueakAGA.hdf/,0
hardfile2=dir,rw,games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF_AGA/BubbleAndSqueakAGA.hdf,32,1,2,512,50,,uae
uaehf1=hdf,rw,DH1:games:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF_AGA/BubbleAndSqueakAGA.hdf,32,1,2,512,50,,uae
```
Compared to this working one -
```
filesystem2=rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
uaehf0=dir,rw,DH0:DH0:/home/pi/RetroPie/roms/amiga-data/_BootWHD/,10
hardfile2=rw,DH1:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,32,1,2,512,0,,uae
uaehf1=hdf,rw,DH1:/home/pi/RetroPie/roms/amiga-data/Games_WHDLoad_HDF/BubbleAndSqueakAGA.hdf,32,1,2,512,0,,uae
```

There are still a lot of differences. `hardfile2` still has `dir`, and it doesn't have DH1: Why do some lines have `games:/` and is the 50 at the end supposed to be 0 ?

(Also when am I supposed to press Ctrl-D or C ? Is what you posted even a Amiga DOS command ? (`dir opt -a DH0: and dir opt -a DH1:`)

**Comment by HoraceAndTheSpider** [comment]
Yes ‘dir’ is the Amiga Dos command to list all files. Possibly the dash is not needed, but I had assumed this might be corrected when you enter it.

the 50 is correct from memory. Keep in mind there are multiple settings here that might work from the Config which are removed by re-saving the file, so I wouldn’t get too concerned about the number. The emulator will correct/limit if needed, but this probably stems back to default values in order versions with specific settings I have given it. 

I will have to put this request regarding HDFs on hold until I can test it directly, But it looks like a misplaced item on the automatic replace/commenting out and nothing major.

**Comment by ghost** [comment]
I temporarily fixed this myself. I changed the hardrive settings from the current `uaeconfig.uaetemp` from this -

```
filesystem2=rw,DH0:DH0:<<inputdir>>_BootWHD/,10
uaehf0=dir,rw,DH0:DH0:<<inputdir>>_BootWHD/,10
filesystem2=rw,DH1:games:<<inputdir>><<hdpath>>/<<game>>/,0
uaehf1=dir,rw,DH1:games:<<inputdir>><<hdpath>>/<<game>>/,0
hardfile2=dir,rw,DH2:HDFGame:<<inputdir>><<hdpath>>/<<game>>,32,1,2,512,50,,uae
uaehf1=hdf,rw,DH2:HDFGame:<<inputdir>><<hdpath>>/<<game>>,32,1,2,512,50,,uae
```
To this -
```
filesystem2=rw,DH0:DH0:<<inputdir>>_BootWHD/,10
uaehf0=dir,rw,DH0:DH0:<<inputdir>>_BootWHD/,10
;filesystem2=rw,DH1:games:<<inputdir>><<hdpath>>/<<game>>/,0
;uaehf1=dir,rw,DH1:games:<<inputdir>><<hdpath>>/<<game>>/,0
hardfile2=rw,DH1:<<inputdir>><<hdpath>>/<<game>>,32,1,2,512,0,,uae
uaehf1=hdf,rw,DH1:<<inputdir>><<hdpath>>/<<game>>,32,1,2,512,0,,uae
```

The `;` probably isn't needed as it comments it out anyway. I hope you can make this change permanent.

I'm not sure why the `games:` and `HDFGame:` was there as this prevented it from finding the correct path.

**Comment by HoraceAndTheSpider** [comment]
Yes, the `;` would need removing from line 3 and 4 in the template as this would otherwise break the standard usage (files rather than HDF) but I will commit the removal of the erroneous `dir,` in line 5 as suggested this evening.

Thanks

**Comment by ghost** [comment]
Please don't think i'm impatient, but did you manage to have a look why the extra settings weren't being applied to the UAE configs (on HDF data only files) ? Surely it could only need a minor tweak ? No worries if you haven't had the time.

**Comment by HoraceAndTheSpider** [comment]
Sorry, my house is literally upside down at the moment (major building works) so i'm pretty much not getting my usual 'evenings' of code!  I am literally just keeping on top of notices and stuff here on my phone!

(occassionally i can spot things on the code there too, but less so...)

I *hope* i get some down-time over this weekend to have a proper look, but cant promise... Config Maker is my main focus at the moment though, since Amiberry will only be bug-fixes up to the next release.

**Comment by ghost** [comment]
Major building works so close to christmas ! I've been there and no what that's like. Thanks for keeping it in mind.

**Comment by ghost** [comment]
I noticed you made a commit concerning this so I tried it but unfortunately it still doesn't work. If you look in the GUI after selecting a game it says this in the Hardrive section -

Device_____Volume_____Path
DH2________n/a_________HDFGame:/home/pi/etc.

It's put the `HDFGame:` part in the path, I take it you haven't had time to test this yet on a Pi ? I think the most important part is can it be made to add the extra settings (like resolution, copper etc.) to the HDF UAE configs ? If it's not possible then it would probably be best to just make the Config Maker scan for Directory Mode only to avoid confusion, otherwise there isn't really much point for HDF's if the configs aren't configured correctly. What do you think on this ?

**Comment by HoraceAndTheSpider** [comment]
I am still working on this. I do need to be able to commit  'not working code' to GitHub though in order to be able to test it, as the updater pulls code from here.

However, the extra settings were being applied to HDFs in my "offline" tests, but this has only been brief so far.

**Comment by ghost** [comment]
Oh, that sounds good news, thanks.

**Comment by ghost** [comment]
I had a quick test and I think it's all working correctly now, thanks for fixing this. I'll check a bit more in a few hours then i'll close this issue. Thanks again.
