### ISSUE TITLE
New folder scanning mode now uses slave name ?

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#48]
This doesn't affect me as I use HDF's but I think it is a minor issue so I thought i'd let you know. When I was testing the .ws issue I tried a select few games in Folder mode. I noticed that one game was using the Slave name instead of the folder/filename. 

`SpaceHarrier&RetrnFntZone` is the folder name but the .uae file that was created was for the Slave name which is different `SpaceHarrier.slave`. This means there is no entry for it in the `UAEConfigMaker_WHD_Longname_Fixes.txt`. I think there are several games that have different folder/slave names.

**Comment by HoraceAndTheSpider** [comment]
Yes currently it uses the slave name because if a pack had multiple slaves (eg Bloodwych and extended levels) it will create a .uae for both.

This is still in testing though and I may revert back to the folder name - there are pros and cons of both. For example, it is useful where a game/data disk has a savegame transfer, but of course on the other side the auto startup file is (currently) shared ... although that may change in the future anyway (a similar “fix” as is needed for HDF)

**Comment by ghost** [comment]
But currently, your booter gives a choice if multiple slaves are found anyway. Would it also be possible to give a choice if a .ws file is found ? So when booting PinballPrelude you have the choice of selecting a Table, otherwise you have to hold down the fire button and reset the boot sequence.

**Comment by HoraceAndTheSpider** [comment]
The activation of the .ws and the slave selector are the same already. Both only appear when the WHDLoad Booter program are activated, and both selections get pushed into auto-startup. So when you pick one of the slave files, it stays like that until manually changed.

To change either, you need to use the hold-fire-down method in order to delete the auto-startup and start the booter up again. 

I find it very strange that Pinball Prelude boots in that way anyway (i guess each table was on separate self-booting disks) , but then the alternative would be 3 slaves for the game, which would have the same behaviour as the above!

**Comment by ghost** [comment]
Oh, I thought they would always come up on the screen if there were mutiple slaves. This means that once you have selected one it will always boot it and you will never know if there was ever a second slave etc. unless you hold down the fire button. And then if your memory was wrong and there wasn't another slave you have to wait until it goes through the boot process again. Another example, am I the only person that's mentioned PinballPrelude since your Booter has been available ? Everyone must think there is only one table because they never had an option :)

**Comment by HoraceAndTheSpider** [comment]
Unfortunately, (or thankfully, depending on your point of view) there is a limit to how much hand-holding one can do for users.  I don't really see this as an issue, or not one that has an practical manner of being addressed.

I will freely admit, there is a level of expectation from myself that if a user is choosing this WHDLoad solution, they should at least understand the concept of WHDLoad, and this is why it is explained in the FAQ via my website for this project. It is even asked on the Facebook groups 'joining questions' ... "what do you think WHDload will do for you?" allowing myself and Admin staff to gauge what level people are pitching at.

It would be no different if the user was using the WHDLoad mode of FS-UAE Launcher (which achieves something very similar), only there they would need to manually change the tooltype command.

I would say that the same applied there when multiple slaves are in use, but actually in those cases its almost impossible to use the second slave (possibly you can if you attach my booter to it, which is FS-UAE compatible) ... at least, i couldnt get it to reselect a different slave when i tried on one game recently.

Getting around the 'not knowing it was there' problem is another reason to scan for .slave files instead of the folders also, because the user will have an entry in Emulation Station for the extra slave files. 


If they do not know about Pinball Prelude needing a custom tool-type for table setting... well.... I cant be responsible for that!  Any option which was introduced to flag this one-off-case to users which have an impact on the load time of all games.

If they like the game enough to routinely play it, they should know it has more than one table IMHO.  If you launch WHDLoad from workbench having set the tooltype to CUSTOM1=3 , do you go in and check the icon's settings every time before loading? The current slave does not have an in-built customisation setting in the slave header, so it would not be seen at all... the .ws file solution at least gives the users a route to make this change. 

Hope this helps to explain the reasoning.

**Comment by ghost** [comment]
Each to their own, just constructive criticism, i'll shut up now. Lastly, Pinball Prelude in Workbench has a separate icon for each table. (And the same for Battle Isle etc.)
