### ISSUE TITLE
When using HDF (data only) mode

### ISSUE THREAD

**Issue by ghost** [HoraceAndTheSpider/UAEConfigMaker#5]
Hi, i'm not on Facebook so I have to post here. A few points -

1) I put my 'data only' HDF files in a 'Games_WHDLoad_HDF' folder (in amiga-data). When running the config maker it doesn't rename the UAE files (the names still have no spaces). If I put the HDF's in same named folders it doesn't detect them. When running the UAE files from EmulationStation, the WHDLoader detects the slave but all I get is a black screen.

2) If I put the HDF's in a 'Games_WHDLoad' folder it doesn't detect them. If I put them in same named folders then it correctly names the UAE files but the WHDLoad booter doesn't detect any slaves.

3) **[please keep to one topic per post, and related to UAE Config Maker only]**

I hope you can sort this out and let me know the correct folder to put Data Only HDF files. Thanks,

**Comment by HoraceAndTheSpider** [comment]
1. The correct folder for HDF's with data is Games_WHDLoad_HDF, although this is relatively untested. If the configs are generating then this implies it is the re-name function is not operating in the HDF mode. Sub-folders are only required for, say , CD32 files where multiple files are for a single game. 

This can be fixed with some example files. Please can you upload approx. 5 'problem' HDFs for testing.

Can you please confirm that the HDFs have the .slave file in the root of the the 'drive' and not a secondart sub-folder?

2. 'Games_WHDLoad' is for game data folders only, so this behaviour would be expected.

3. I have removed comment regarding the WHDBoot Loader, as this platform/GitHub is for the UAE Config Maker specifically. Files provided are readily available via internet sources, including google searches. These are not included within this GitHub repo.

Thanks

**Comment by ghost** [comment]
1) I created the HDF's with RareJay's WHDLoad ZIP/LHA to HDF script. The slave file is not on the root. Example.

Game:
.....AladdinAGA
..........AladdinAGA.Slave

https://drive.google.com/file/d/0B749yVJTt5YMNlVzZURMY2RFNU0/view?usp=sharing

**Comment by HoraceAndTheSpider** [comment]
This will be the reason for the problem. The Booter requires the .slave file to be in the root of the drive. Although I can look into this for recursive scanning (which will be slower, being amiga-side), it is again  not part of this repo.  As i understand, the xdftool will create HDF files for you in this way http://lallafa.de/blog/amiga-projects/amitools/xdftool/

This issue will be marked as resolved once the naming bug is fixed.

Thanks

**Comment by windale** [comment]
So the xdftool can batch convert RetroPlay's WHDLoad LHA files to HDF ??? 

![bios files](https://cloud.githubusercontent.com/assets/12862298/25182689/5baa8c48-250d-11e7-8052-efea97d986db.png)
ILLEGAL

**Comment by HoraceAndTheSpider** [comment]
Yes.

If you continue to post as you are i will be deleting this thread completely. As i said, this is not a place to post regarding the WHDBooter, which will now be change due to your petty behaviour. 

So well done on ruining the project for all involved.

**Comment by HoraceAndTheSpider** [comment]
The files that have so offended your hypocracy @windale have been removed.

Perhaps you should consider why this petty behaviour is so important to you and why you feel the need to make things more difficult for hundreds of other users. 

This requested change will now go to the bottom of the priority list.

**Comment by windale** [comment]
What is wrong with you Dom ? What is this supposed to mean ? 

> The files that have so offended your hypocracy @windale have been removed.

Do you even know what i'm talking about ?
You say to everyone you cannot distribute the roms needed because of legal reasons, but in your WHDLoad Booter program https://drive.google.com/file/d/0B4272ME-kTRMT2wwbzUxb29UMVk/view in the kickstarts directory are the same BIOS files, they are just renamed. Gamebase Amiga was distributed without these as well. I thought I was being helpful by telling this but then you've come back with yet another sarcastic answer. So what files did you remove because it wasn't the ones I was talking about. Please give me an explanation and an apology.

**Comment by osvaldolove** [comment]
Hi - I think this thread is going a off topic.
Some of the issues raised were for another project and not related to this one.

As I am a contributor to this project I get all these emails and they aren't constructive.
Can we keep reported issues relevant to the UAEConfigMaker.
Thanks :)

**Comment by HoraceAndTheSpider** [comment]
For crying out loud @windale  Yes, i know what you are talking about. and trust me there is no sarcasm here - i owe you no apology when your intent is purely to stir up hassle and will lead to you being blocked from the group.

The **linked** file for the booter is actually here:  
http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/downloads/WHDLoad%20Booter.zip

This is the one you will find referenced through all the guide documents.

To satisfy your petty behaviour, i have removed the offending files from this DISTRIBUTED LINK.  The Google Drive file has not been used in some time, and is now also deleted.

You are a hypocrite because you are quite happy to post game data files as well, and no doubt download those yourself, but have decided to make an issue out of this....

**Comment by HoraceAndTheSpider** [comment]
Naming bug fixed on develop branch.
